<?php $base=''; $title='تواصل معنا'; $active='contact'; include 'partials/head.php'; include 'partials/nav.php'; ?>
<main id="main" data-contact-page data-api="api/contact.php" aria-busy="true">
<section class="page-hero page-hero-simple" data-contact-section="hero"><div class="hero-dots"></div><div class="container"><span class="eyebrow reveal" data-contact-hero-eyebrow>نحن هنا</span><h1 class="reveal mt-16" data-contact-hero-title>تواصل مع فريق Seven Tech Capital</h1><p class="reveal" data-contact-hero-description>استفسارات المستثمرين ورواد الأعمال والشراكات — نجيبك في أقرب وقت.</p></div></section>
<section class="section contact-section" data-contact-section="contact"><div class="container"><div class="contact-layout">
  <div class="card card-pad-lg contact-form-card reveal"><div class="content-card-head"><span class="content-card-kicker" data-contact-form-kicker>راسلنا مباشرة</span><h2 data-contact-form-title>أرسل رسالة</h2><p data-contact-form-description>شاركنا تفاصيل استفسارك وسيوجّه الفريق رسالتك إلى الشخص المناسب.</p></div>
    <form class="mt-24" data-contact-form novalidate><div class="form-grid"><div class="field"><label class="label" for="c-name"><span data-contact-name-label>الاسم</span> <span class="req">*</span></label><input class="input" id="c-name" name="name" autocomplete="name" required minlength="2" maxlength="180" placeholder="اسمك…"></div><div class="field"><label class="label" for="c-email"><span data-contact-email-label>البريد</span> <span class="req">*</span></label><input class="input" id="c-email" name="email" type="email" inputmode="email" autocomplete="email" spellcheck="false" required maxlength="250" placeholder="you@example.com…"></div></div>
      <div class="form-grid"><div class="field"><label class="label" for="c-tel" data-contact-whatsapp-label>رقم واتساب</label><input class="input ltr-input" id="c-tel" name="whatsapp" type="tel" inputmode="tel" autocomplete="tel" spellcheck="false" maxlength="60" placeholder="+966539555889"></div><div class="field"><label class="label" for="c-type" data-contact-topic-label>نوع الاستفسار</label><select class="select" id="c-type" name="topic" required><option value="investor">استفسار مستثمر</option><option value="project">تقديم مشروع</option><option value="partnership">شراكة استراتيجية</option><option value="media">إعلامي / صحفي</option><option value="general">عام</option></select></div></div>
      <div class="field"><label class="label" for="c-msg"><span data-contact-message-label>الرسالة</span> <span class="req">*</span></label><textarea class="textarea" id="c-msg" name="message" required minlength="10" maxlength="5000" placeholder="كيف يمكننا مساعدتك؟"></textarea></div>
      <div aria-hidden="true" style="position:absolute;left:-10000px;width:1px;height:1px;overflow:hidden"><label for="c-website">Website</label><input id="c-website" name="website" type="text" tabindex="-1" autocomplete="off"></div>
      <button class="btn btn-primary btn-lg btn-block" type="submit" data-contact-submit-label>إرسال الرسالة</button><div data-contact-result role="status" aria-live="polite" hidden></div>
    </form>
  </div>
  <aside class="contact-sidebar reveal" aria-label="بيانات التواصل">
    <div class="card contact-info-card"><div class="row gap-12"><div class="sector-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z"/><path d="M22 6l-10 7L2 6"/></svg></div><div><b data-contact-email-title>البريد الإلكتروني</b><a class="text-2 contact-value" data-contact-email href="mailto:hello@seventech.capital">hello@seventech.capital</a></div></div></div>
    <div class="card contact-info-card"><div class="row gap-12"><div class="sector-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/></svg></div><div><b data-contact-whatsapp-title>واتساب</b><a class="text-2 ltr-number contact-value" data-contact-whatsapp href="https://wa.me/966539555889">+966539555889</a></div></div></div>
    <div class="card contact-offices"><b data-contact-offices-title>المكاتب</b><div class="office-list" data-contact-offices><div class="office-row"><span class="badge badge-orange">القاهرة</span><span class="text-2">مصر — المقر الرئيسي</span></div><div class="office-row"><span class="badge badge-info">دبي</span><span class="text-2">الإمارات — قيد التوسع</span></div><div class="office-row"><span class="badge badge-success">الرياض</span><span class="text-2">السعودية — مستهدف</span></div></div></div>
    <div class="contact-notice"><p data-contact-notice>كيان قيد التأسيس واستكمال التراخيص — لا يُستقبل تمويل قبل الاعتماد القانوني.</p></div>
  </aside>
</div></div></section>
</main>
<script src="assets/js/contact-page.js?v=20260901-sections" defer></script>
<?php include 'partials/footer.php'; ?>

