<?php
require_once __DIR__.'/../lib/contact-page-sections.php';require_once __DIR__.'/content-editor-fields.php';try{$contactSections=contact_page_read();$contactMessages=contact_page_messages();}catch(Throwable $error){error_log('Contact editor: '.$error->getMessage());echo '<div class="auth-message auth-message-error">تعذر تحميل المحتوى. شغّل MySQL في MAMP ثم أعد تحميل الصفحة.</div>';return;}
?>
<link rel="stylesheet" href="../assets/css/home-editor.css?v=<?= filemtime(__DIR__.'/../assets/css/home-editor.css') ?>">
<div class="home-manager" data-home-manager data-endpoint="../api/admin-contact-sections.php">
  <div class="panel home-manager-intro"><div><h3>التحكم في صفحة تواصل معنا</h3><p>عدّل المقدمة والنموذج وبيانات التواصل ثم اضغط «حفظ ونشر القسم».</p><p class="hint">يمكنك إضافة أنواع الاستفسارات والمكاتب وترتيبها وإظهارها أو إخفاؤها. رسائل الزوار محفوظة أسفل المحرر.</p></div><a href="../contact.php" target="_blank" rel="noopener" class="btn btn-ghost">معاينة الصفحة ↗</a></div>
  <nav class="home-editor-nav" aria-label="أقسام صفحة تواصل معنا"><?php foreach(contact_page_schema() as $key=>$schema):?><a href="#edit-<?= $key ?>" class="btn btn-soft btn-sm"><?= home_escape($schema['label']) ?></a><?php endforeach;?></nav>
  <div class="home-editor-sections"><?php foreach(contact_page_schema() as $key=>$schema):$section=$contactSections[$key];?><details class="home-editor-section" id="edit-<?= $key ?>"><summary><span><?= home_escape($schema['label']) ?></span><span class="badge" data-section-state><?= $section['content']['is_active']?'ظاهر':'مخفي' ?></span></summary><form data-home-form data-section="<?= $key ?>" data-revision="<?= (int)$section['revision'] ?>" class="home-editor-form"><input type="hidden" name="csrf" value="<?= home_escape(auth_csrf_token()) ?>"><?php home_editor_fields($schema['fields'],$section['content']);?><div class="home-save-row"><span role="status" aria-live="polite" data-home-result>المحتوى المحفوظ حاليًا</span><button type="submit" class="btn btn-primary">حفظ ونشر القسم</button></div></form></details><?php endforeach;?></div>
</div>
<div class="panel mt-24"><div class="panel-head"><div><h3>رسائل الزوار</h3><p class="hint">آخر 30 رسالة أُرسلت من نموذج تواصل معنا.</p></div><span class="badge"><?= count($contactMessages) ?> رسالة</span></div><div class="panel-body"><?php foreach($contactMessages as $message):?><details class="home-editor-item"><summary><span><?= home_escape($message['name'].' — '.$message['topic_label']) ?></span><span class="hint"><?= home_escape($message['created_at']) ?></span></summary><div class="home-editor-item-body"><p><b>البريد:</b> <a href="mailto:<?= home_escape($message['email']) ?>"><?= home_escape($message['email']) ?></a></p><?php if($message['whatsapp']!==''):?><p><b>واتساب:</b> <span class="ltr-number"><?= home_escape($message['whatsapp']) ?></span></p><?php endif;?><p><?= nl2br(home_escape($message['message'])) ?></p></div></details><?php endforeach;?><?php if(!$contactMessages):?><div class="empty-state"><b>لا توجد رسائل بعد</b><p>ستظهر الرسائل هنا فور إرسالها من نموذج التواصل.</p></div><?php endif;?></div></div>
<script src="../assets/js/admin-home.js?v=<?= filemtime(__DIR__.'/../assets/js/admin-home.js') ?>" defer></script>
