<?php
$entrepreneurPageSections=['hero'=>'مقدمة الصفحة','stages_header'=>'مقدمة مراحل الدعم','stage'=>'مراحل الدعم','evaluation_header'=>'مقدمة التقييم','criterion'=>'معايير التقييم','review_header'=>'بطاقة المراجعة','review_step'=>'خطوات المراجعة','apply_header'=>'مقدمة نموذج التقديم','support_option'=>'أنواع الدعم'];
$entrepreneurPageIcons=['default'=>'بدون أيقونة','check'=>'علامة تحقق','layers'=>'طبقات الدعم'];
$entrepreneurPageStyles=['info'=>'عادي','orange'=>'بارز/مكتمل','success'=>'أخضر','warning'=>'ذهبي'];
?>
<div class="panel admin-knowledge-manager admin-entrepreneurs-page-manager" data-admin-entrepreneurs-page-manager>
  <div class="panel-head"><div><h3>إدارة صفحة رواد الأعمال</h3><p class="hint">تحكم في المقدمة والمراحل والمعايير وخط المراجعة وأنواع الدعم عبر API.</p></div><span class="badge"><?= count($entrepreneurPageItems) ?> عنصر</span></div>
  <div class="panel-body">
    <details class="admin-sector-create admin-knowledge-create"><summary><span>إضافة عنصر جديد</span><small>اختر القسم ثم أدخل المحتوى</small></summary>
      <form method="post" class="admin-sector-create-form admin-knowledge-form" data-admin-entrepreneurs-page-form><input type="hidden" name="csrf" value="<?= htmlspecialchars(auth_csrf_token()) ?>"><input type="hidden" name="action" value="create_entrepreneur_page_item">
        <div class="admin-knowledge-fields"><div class="field"><label class="label">القسم</label><select class="select" name="section_key"><?php foreach($entrepreneurPageSections as $value=>$label): ?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach; ?></select></div><div class="field"><label class="label">العنوان</label><input class="input" name="title" required></div><div class="field"><label class="label">العنوان الفرعي</label><input class="input" name="subtitle"></div><div class="field"><label class="label">نص الزر الأول / الشارة</label><input class="input" name="badge_label"></div></div>
        <div class="field"><label class="label">الوصف</label><textarea class="textarea" name="body"></textarea></div>
        <div class="admin-knowledge-fields"><div class="field"><label class="label">نص الزر الثاني / علامة الحالة</label><input class="input" name="value_text"></div><div class="field"><label class="label">ملخص جانب المقدمة — افصل بـ |</label><input class="input" name="value_suffix" placeholder="تقييم واضح|6 مراحل دعم|وصف مختصر"></div><div class="field"><label class="label">الأيقونة</label><select class="select" name="icon_key"><?php foreach($entrepreneurPageIcons as $value=>$label): ?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach; ?></select></div><div class="field"><label class="label">نمط العنصر</label><select class="select" name="badge_style"><?php foreach($entrepreneurPageStyles as $value=>$label): ?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach; ?></select></div><div class="field"><label class="label">الرابط الأول</label><input class="input ltr-input" name="primary_url"></div><div class="field"><label class="label">الرابط الثاني</label><input class="input ltr-input" name="secondary_url"></div></div>
        <div class="admin-knowledge-footer"><label class="auth-check"><input type="checkbox" name="is_active" value="1" checked><span>ظاهر في الموقع</span></label><div class="field"><label class="label">الترتيب</label><input class="input" type="number" min="0" name="sort_order" value="<?= count($entrepreneurPageItems)+1 ?>" required></div><button class="btn btn-primary btn-sm" type="submit">إضافة العنصر</button></div>
      </form>
    </details>
    <div class="admin-knowledge-editor-grid mt-24">
      <?php foreach($entrepreneurPageItems as $item): ?>
        <form method="post" class="admin-knowledge-editor-card" data-admin-entrepreneurs-page-form><input type="hidden" name="csrf" value="<?= htmlspecialchars(auth_csrf_token()) ?>"><input type="hidden" name="id" value="<?= htmlspecialchars($item['id']) ?>">
          <div class="admin-knowledge-card-head"><span class="badge"><?= htmlspecialchars($entrepreneurPageSections[$item['section_key']]??$item['section_key']) ?></span><label class="auth-check"><input type="checkbox" name="is_active" value="1" <?= !empty($item['is_active'])?'checked':'' ?>><span>ظاهر</span></label></div>
          <div class="admin-knowledge-fields"><div class="field"><label class="label">القسم</label><select class="select" name="section_key"><?php foreach($entrepreneurPageSections as $value=>$label): ?><option value="<?= $value ?>" <?= $item['section_key']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><div class="field"><label class="label">العنوان</label><input class="input" name="title" value="<?= htmlspecialchars($item['title']) ?>" required></div><div class="field"><label class="label">العنوان الفرعي</label><input class="input" name="subtitle" value="<?= htmlspecialchars($item['subtitle']) ?>"></div><div class="field"><label class="label">نص الزر الأول / الشارة</label><input class="input" name="badge_label" value="<?= htmlspecialchars($item['badge_label']) ?>"></div></div>
          <div class="field"><label class="label">الوصف</label><textarea class="textarea" name="body"><?= htmlspecialchars($item['body']) ?></textarea></div>
          <div class="admin-knowledge-fields"><div class="field"><label class="label">نص الزر الثاني / الحالة</label><input class="input" name="value_text" value="<?= htmlspecialchars($item['value_text']) ?>"></div><div class="field"><label class="label">ملخص جانب المقدمة</label><input class="input" name="value_suffix" value="<?= htmlspecialchars($item['value_suffix']) ?>"></div><div class="field"><label class="label">الأيقونة</label><select class="select" name="icon_key"><?php foreach($entrepreneurPageIcons as $value=>$label): ?><option value="<?= $value ?>" <?= $item['icon_key']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><div class="field"><label class="label">نمط العنصر</label><select class="select" name="badge_style"><?php foreach($entrepreneurPageStyles as $value=>$label): ?><option value="<?= $value ?>" <?= $item['badge_style']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><div class="field"><label class="label">الرابط الأول</label><input class="input ltr-input" name="primary_url" value="<?= htmlspecialchars($item['primary_url']) ?>"></div><div class="field"><label class="label">الرابط الثاني</label><input class="input ltr-input" name="secondary_url" value="<?= htmlspecialchars($item['secondary_url']) ?>"></div><div class="field admin-knowledge-order"><label class="label">الترتيب</label><input class="input" type="number" min="0" name="sort_order" value="<?= (int)$item['sort_order'] ?>" required></div></div>
          <div class="admin-sector-editor-actions"><button class="btn btn-primary btn-sm" type="submit" name="action" value="update_entrepreneur_page_item">حفظ التعديلات</button><button class="btn btn-sm admin-delete-button" type="submit" name="action" value="delete_entrepreneur_page_item" formnovalidate onclick="return confirm('هل أنت متأكد من حذف هذا العنصر من صفحة رواد الأعمال؟')">حذف العنصر</button></div>
        </form>
      <?php endforeach; ?>
    </div>
  </div>
</div>
